
ALTER TABLE FACTURE
ADD CONSTRAINT FK_FAC_LIG FOREIGN KEY (numCompte) REFERENCES LIGUE(numCompte);

ALTER TABLE LIGNE_FACTURE
ADD CONSTRAINT FK_LIGNE_FACT_FACT FOREIGN KEY(numFact)
REFERENCES FACTURE(numFact),
ADD CONSTRAINT FK_LIGNE_FACT_PRESTA FOREIGN KEY(codePresta)
REFERENCES PRESTATION(codePresta);
