DROP FUNCTION IF EXISTS affprixht;
DELIMITER @
CREATE FUNCTION affprixht(unprixht DECIMAL(3,2))
RETURNS DECIMAL (3,2)
LANGUAGE SQL
DETERMINISTIC
BEGIN	
	RETURN CONCAT(unprixht*1.2);
END;
@
DELIMITER ;